FROM ubuntu:24.04 as build

ARG FEATURES

RUN apt-get clean && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    apt-get install -y curl build-essential

RUN apt-get install -y rustup
RUN rustup default stable
RUN sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.7/install)" && \
    /root/.local/share/solana/install/active_release/bin/sdk/sbf/scripts/install.sh

ENV PATH=${PATH}:/root/.local/share/solana/install/active_release/bin

COPY hello_world /opt/hello_world

WORKDIR /opt/hello_world/program
RUN cargo test
RUN cargo build-sbf

FROM anzaxyz/agave:v2.1.7
COPY --from=build /opt/hello_world/target/deploy/hello_world.so /opt/
COPY --from=build /opt/hello_world/ci /opt/ci

ENTRYPOINT [ "/opt/ci/start_solana.sh" ]



